apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-slovenija
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: parlassets-slovenija
    newName: rg.fr-par.scw.cloud/djnd/parlassets-slovenija
    newTag: 'a8e985b7ec73cd70be181b77b20e3eee37a18eab'
